# Generated by Django 4.1.3 on 2022-12-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('title_pt_br', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_pt_br', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
